const API_BASE_URL = "http://127.0.0.1:8000";
const LOW_THRESHOLD = 0.2;
const MODERATE_THRESHOLD = 0.55;
const $ = (id) => document.getElementById(id);

const state = { file: null, files: [], results: [], data: null, signal: [], selectedMetric: null, chartReady: false };
const number = (value, digits = 2) => Number(value).toLocaleString(undefined, { minimumFractionDigits: digits, maximumFractionDigits: digits });
const finite = (value) => Number.isFinite(Number(value)) ? Number(value) : null;
const esc = (value) => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));

function notify(message, error = false) { const toast = $("toast"); toast.textContent = message; toast.className = `toast${error ? " error" : ""}`; clearTimeout(notify.timer); notify.timer = setTimeout(() => toast.classList.add("hidden"), 5000); }
function conditionFor(damage) { if (damage < LOW_THRESHOLD) return { label: "LOW FATIGUE / NORMAL OPERATIONAL WEAR", short: "Low fatigue", className: "low", color: "#59d49b", action: "No urgent action is indicated. Continue routine monitoring and the normal inspection schedule." }; if (damage <= MODERATE_THRESHOLD) return { label: "MODERATE WEAR / MONITOR AT SERVICE", short: "Monitor", className: "moderate", color: "#f7c65d", action: "Record this result and ask the maintenance team to check the structure at the next planned service." }; return { label: "HIGH WEAR / PRIORITY INSPECTION", short: "Priority", className: "high", color: "#ff7479", action: "Flag this result for the maintenance lead and arrange an engineering inspection before the next service run." }; }

async function checkBackendHealth() { const indicator = $("backendStatus"); indicator.className = "connection checking"; indicator.innerHTML = "<i></i><span>Checking SHM API</span>"; try { const response = await fetch(`${API_BASE_URL}/health`, { signal: AbortSignal.timeout(3500) }); const payload = await response.json(); if (!response.ok || payload.status !== "ok") throw new Error(); indicator.className = "connection online"; indicator.innerHTML = "<i></i><span>SHM API connected</span>"; } catch { indicator.className = "connection offline"; indicator.innerHTML = "<i></i><span>SHM API offline</span>"; } }
async function runSHMPrediction(upload) { const form = new FormData(); form.append("file", upload, upload.name); let response; try { response = await fetch(`${API_BASE_URL}/predict`, { method: "POST", body: form, signal: AbortSignal.timeout(120000) }); } catch { throw new Error("RailOps could not reach the SHM analysis server. Confirm that FastAPI is running on port 8000."); } let payload = {}; try { payload = await response.json(); } catch { } if (!response.ok) throw new Error(payload.detail || "Prediction request failed. Check the sensor CSV and try again."); return payload; }

function wireDropZone(zoneId, inputId, buttonId, handler) { const zone = $(zoneId); const input = $(inputId); $(buttonId).onclick = (event) => { event.stopPropagation(); input.click(); }; zone.onclick = () => input.click(); input.onchange = () => handler([...input.files]); ["dragenter", "dragover"].forEach((type) => zone.addEventListener(type, (event) => { event.preventDefault(); zone.classList.add("dragging"); })); ["dragleave", "drop"].forEach((type) => zone.addEventListener(type, () => zone.classList.remove("dragging"))); zone.addEventListener("drop", (event) => { event.preventDefault(); handler([...event.dataTransfer.files]); }); }
function stageSingle(upload) { if (!upload || !/\.csv$/i.test(upload.name)) return notify("Please choose a CSV sensor file.", true); state.file = upload; $("singleWork").classList.remove("hidden"); $("fileName").textContent = upload.name; $("fileMeta").textContent = `${(upload.size / 1048576).toFixed(2)} MB Â· ready for analysis`; resetResults(); notify(`${upload.name} is ready for assessment.`); }
function stageBatch(selected) { state.files = selected.filter((upload) => /\.csv$/i.test(upload.name)); if (!state.files.length) return notify("Choose one or more CSV sensor files.", true); $("batchWork").classList.remove("hidden"); $("batchCount").textContent = `${state.files.length} file${state.files.length === 1 ? "" : "s"} ready`; $("fileList").innerHTML = state.files.map((upload) => `<div><span>${esc(upload.name)}</span><small>${(upload.size / 1048576).toFixed(2)} MB</small></div>`).join(""); $("batchResults").classList.add("hidden"); }
function resetResults() { state.data = null; state.signal = []; state.selectedMetric = null; $("resultWaiting").classList.remove("hidden"); $("resultData").classList.add("hidden"); $("summary").classList.add("hidden"); $("whyPanel").classList.add("hidden"); $("chartEmpty").classList.remove("hidden"); $("chartText").textContent = "Awaiting analysis"; if (state.chartReady) Plotly.purge("wave"); state.chartReady = false; document.querySelectorAll(".metric,.context-item").forEach((item) => item.classList.remove("selected")); }
function renderMetrics(data) { const values = { samples: finite(data.total_samples), mean: finite(data.mean_stress), max: finite(data.max_stress), min: finite(data.min_stress), rms: finite(data.rms) }; $("samples").textContent = values.samples === null ? "â€”" : Math.round(values.samples).toLocaleString(); $("mean").textContent = values.mean === null ? "â€”" : `${number(values.mean)} MPa`; $("max").textContent = values.max === null ? "â€”" : `${number(values.max)} MPa`; $("min").textContent = values.min === null ? "â€”" : `${number(values.min)} MPa`; $("rms").textContent = values.rms === null ? "â€”" : `${number(values.rms)} MPa`; $("range").textContent = values.max === null || values.min === null ? "â€”" : `${number(values.max - values.min)} MPa`; const contextValues = { contextMax: values.max, contextMin: values.min, contextMean: values.mean, contextRms: values.rms, contextRange: values.max === null || values.min === null ? null : values.max - values.min }; Object.entries(contextValues).forEach(([id, value]) => { $(id).textContent = value === null ? "â€”" : `${number(value)} MPa`; }); $("contextDamage").textContent = number(data.prediction, 3); }
function renderDamage(data) { const damage = Math.max(0, Math.min(1, finite(data.prediction ?? data.damage ?? data.D))); const condition = conditionFor(damage); $("resultWaiting").classList.add("hidden"); $("resultData").classList.remove("hidden"); $("conditionDot").className = condition.className; $("health").textContent = condition.label; $("damage").textContent = damage.toFixed(3); $("fill").style.width = `${damage * 100}%`; $("fill").style.background = condition.color; $("action").textContent = condition.action; $("fileMeta").textContent = `${(state.file.size / 1048576).toFixed(2)} MB Â· ${finite(data.total_samples)?.toLocaleString() || ""} readings processed`; return condition; }
function renderSummary(data, condition) { $("diagnosticText").textContent = data.explanation || `The signal is classified as ${condition.short.toLowerCase()}. Review the measurements below for the context of this assessment.`; $("recommendation").textContent = data.recommendation || condition.action; $("summary").classList.remove("hidden"); }

function renderSignalChart(signal) { const values = signal.map(Number).filter(Number.isFinite); if (!values.length) return; const step = Math.max(1, Math.ceil(values.length / 1800)); state.signal = values.filter((_, index) => index % step === 0); state.chartReady = true; $("chartEmpty").classList.add("hidden"); $("chartText").textContent = `${state.signal.length.toLocaleString()} displayed samples`; const x = state.signal.map((_, index) => index * step + 1); Plotly.newPlot("wave", [{ x, y: state.signal, type: "scattergl", mode: "lines", line: { color: "#65d9e8", width: 1.4 }, fill: "tozeroy", fillcolor: "rgba(101,217,232,.07)", hovertemplate: "Sample %{x:,}<br>Stress %{y:.2f} MPa<extra></extra>" }], { margin: { l: 52, r: 18, t: 12, b: 42 }, paper_bgcolor: "transparent", plot_bgcolor: "transparent", hovermode: "x", dragmode: "zoom", showlegend: false, xaxis: { title: "Sample index", color: "#8da5ae", gridcolor: "#1d3742", zeroline: false }, yaxis: { title: "Stress / MPa", color: "#8da5ae", gridcolor: "#1d3742", zeroline: false }, font: { family: "Manrope", color: "#edf5f4" } }, { responsive: true, displaylogo: false, modeBarButtonsToRemove: ["lasso2d", "select2d"] }); }
function selectMetric(metric) { if (!state.data) return; state.selectedMetric = state.selectedMetric === metric ? null : metric; document.querySelectorAll(".metric,.context-item").forEach((item) => item.classList.toggle("selected", item.dataset.metric === state.selectedMetric)); const explanations = { samples: "Total readings is the number of valid sensor observations processed by the backend.", mean: "Mean stress is the average stress level across the recording. It is shown as a reference line on the graph.", max: "Peak stress is the highest recorded stress. One peak may be a short loading event; repeated large excursions can contribute more to wear.", min: "Minimum stress is the lowest recorded stress in the measurement window. It helps show the full span of the signal.", rms: "RMS stress is a measure of the overall magnitude of the signal. It is an intensity indicator, not a failure threshold.", range: "Stress range is the span between the highest and lowest recorded values. A wider span means the signal moved through a larger band." }; $("whyText").textContent = explanations[metric] || "Select a measurement to see a plain-English explanation."; $("whyPanel").classList.remove("hidden"); if (metric === "max" || metric === "min") highlightPoint(metric); else if (metric === "mean" || metric === "rms") drawReference(metric); else Plotly.relayout("wave", { shapes: [] }); }
function highlightPoint(metric) { const values = state.signal; const index = metric === "max" ? values.indexOf(Math.max(...values)) : values.indexOf(Math.min(...values)); if (index < 0) return; const point = { x: [index + 1], y: [values[index]], type: "scatter", mode: "markers", marker: { color: metric === "max" ? "#ff7479" : "#f7c65d", size: 11, line: { color: "#08151e", width: 3 } }, hovertemplate: `${metric === "max" ? "Peak" : "Minimum"}<br>Sample %{x:,}<br>Stress %{y:.2f} MPa<extra></extra>` }; const graph = $("wave"); const removeMarker = graph.data && graph.data.length > 1 ? Plotly.deleteTraces("wave", [1]) : Promise.resolve(); removeMarker.then(() => Plotly.addTraces("wave", [point])); }
function drawReference(metric) { const value = metric === "mean" ? finite(state.data.mean_stress) : finite(state.data.rms); if (value === null) return; Plotly.relayout("wave", { shapes: [{ type: "line", x0: 0, x1: 1, xref: "paper", y0: value, y1: value, line: { color: metric === "mean" ? "#f7c65d" : "#b99cff", width: 2, dash: "dot" } }] }); }

async function handleSingleRun() { if (!state.file) return; const button = $("runSingle"); button.disabled = true; button.innerHTML = "<span class=\"spinner\"></span> Reading sensor dataâ€¦"; try { const data = await runSHMPrediction(state.file); const prediction = finite(data.prediction ?? data.damage ?? data.D); if (prediction === null) throw new Error("The analysis server returned no fatigue score."); state.data = data; const condition = renderDamage(data); renderMetrics(data); renderSummary(data, condition); renderSignalChart(Array.isArray(data.preview_signal) ? data.preview_signal : []); checkBackendHealth(); notify("Diagnostic complete."); } catch (error) { notify(error.message, true); } finally { button.disabled = false; button.innerHTML = "Run diagnostic <span>â†’</span>"; } }
async function handleBatchRun() { if (!state.files.length) return; const button = $("runBatch"); button.disabled = true; state.results = []; try { for (let index = 0; index < state.files.length; index += 1) { button.innerHTML = `<span class=\"spinner\"></span> Processing ${index + 1} of ${state.files.length}â€¦`; const data = await runSHMPrediction(state.files[index]); const prediction = finite(data.prediction ?? data.damage ?? data.D); if (prediction === null) throw new Error(`${state.files[index].name}: prediction missing.`); state.results.push({ file_id: data.file_id || state.files[index].name, prediction }); } showBatchResults(); notify(`${state.results.length} files processed successfully.`); } catch (error) { notify(error.message, true); } finally { button.disabled = false; button.innerHTML = "Run batch inference <span>â†’</span>"; } }
function showBatchResults() { $("rows").innerHTML = state.results.map((item) => { const condition = conditionFor(item.prediction); return `<tr><td>${esc(item.file_id)}</td><td>${item.prediction.toFixed(6)}</td><td><span class="status-pill ${condition.className}">${condition.short}</span></td></tr>`; }).join(""); $("batchResults").classList.remove("hidden"); }
function downloadSubmissionCSV() { const text = `file_id,prediction\n${state.results.map((item) => `${item.file_id},${item.prediction.toFixed(6)}`).join("\n")}\n`; const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob([text], { type: "text/csv" })); link.download = "shm_predictions.csv"; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 0); }

wireDropZone("singleDrop", "singleFile", "pickSingle", (items) => stageSingle(items[0])); wireDropZone("batchDrop", "batchFiles", "pickBatch", stageBatch); $("runSingle").onclick = handleSingleRun; $("runBatch").onclick = handleBatchRun; $("download").onclick = downloadSubmissionCSV; $("clearFile").onclick = () => { state.file = null; $("singleFile").value = ""; $("singleWork").classList.add("hidden"); resetResults(); }; document.querySelectorAll(".metric,.context-item").forEach((item) => item.onclick = () => selectMetric(item.dataset.metric)); $("whyToggle").onclick = () => { const panel = $("whyPanel"); panel.classList.toggle("hidden"); $("whyToggle").setAttribute("aria-expanded", String(!panel.classList.contains("hidden"))); }; $("closeWhy").onclick = () => $("whyPanel").classList.add("hidden"); $("resetChart").onclick = () => { if (state.chartReady) { Plotly.relayout("wave", { shapes: [] }); if ($("wave").data && $("wave").data.length > 1) Plotly.deleteTraces("wave", [1]); Plotly.relayout("wave", { "xaxis.autorange": true, "yaxis.autorange": true }); } state.selectedMetric = null; document.querySelectorAll(".metric,.context-item").forEach((item) => item.classList.remove("selected")); $("whyText").textContent = "Select a measurement to see a plain-English explanation."; }; document.querySelectorAll(".view-tab").forEach((button) => button.onclick = () => { document.querySelectorAll(".view-tab,.view").forEach((item) => item.classList.remove("active")); button.classList.add("active"); $(button.dataset.tab).classList.add("active"); }); document.querySelectorAll(".system").forEach((button) => button.onclick = () => { if (button.classList.contains("unavailable")) return notify(`${button.dataset.name} is planned for a future release.`); document.querySelectorAll(".system").forEach((item) => item.classList.remove("active")); button.classList.add("active"); $("shm").classList.toggle("hidden", button.dataset.view !== "shm"); $("door").classList.toggle("hidden", button.dataset.view !== "door"); }); $("pickDoor").onclick = () => $("doorFile").click(); $("doorFile").onchange = async () => { const upload = $("doorFile").files[0]; if (!upload) return; $("doorOutput").classList.remove("hidden"); $("doorOutput").textContent = "Door analysis is not available in the current API."; notify("Door analysis is not available in the current API.", true); };
checkBackendHealth(); setInterval(checkBackendHealth, 30000);


