from typing import Dict, Any

def generate_engineering_explanation(profile: Dict[str, Any], features: Dict[str, Any], predicted_damage: float) -> str:
    """
    Generates a human-readable, domain-grounded engineering diagnostic explanation
    of the signal, extracted fatigue cycles, and the estimated cumulative damage.
    
    Acts as the non-authoritative explanation layer (does not alter the numeric prediction).
    """
    ptp = profile['peak_to_peak']
    rms = profile['rms_stress']
    max_range = features.get('rf_max_range', ptp)
    total_cycles = features.get('rf_total_cycles', 0)
    
    # Assess severity tier
    if predicted_damage < 0.10:
        severity = "Normal / Low Risk"
        rec = "No immediate maintenance action required. Continue regular inspection interval."
        cycle_impact = "The stress reversals are predominantly low-amplitude, causing minimal fatigue accumulation."
    elif predicted_damage < 0.35:
        severity = "Moderate Risk (Elevated Fatigue)"
        rec = "Recommend scheduled non-destructive evaluation (NDE) on bogie weld seams during next depot turnaround."
        cycle_impact = "Moderate-amplitude stress cycles were detected, contributing to steady structural fatigue progression."
    else:
        severity = "Critical Wear / High Fatigue Risk"
        rec = "High priority maintenance flag: Perform ultrasonic/magnetic particle inspection of critical structural joints immediately."
        cycle_impact = "High-amplitude stress reversals were recorded with high cycle power accumulation, indicating severe dynamic loading conditions."

    explanation = f"""
### 📋 Engineering Diagnostic Report

* **Operating Assessment**: **{severity}**
* **Estimated Cumulative Fatigue Damage ($D$)**: **`{predicted_damage:.4f}`**

---

#### 🔍 Signal & Fatigue Dynamics
1. **Dynamic Stress Range**: Peak-to-peak variation of **`{ptp:.2f} MPa`** (Peak: `{profile['max_stress']:.2f} MPa`, Valley: `{profile['min_stress']:.2f} MPa`) with an RMS stress level of **`{rms:.2f} MPa`**.
2. **Cycle Reversals (ASTM Rainflow)**: **`{int(total_cycles):,}`** turning cycles counted with a maximum stress range of **`{max_range:.2f} MPa`**.
3. **Fatigue Mechanism**: {cycle_impact}

---

#### 💡 Maintenance Recommendation
> {rec}

*Note: This explanation is generated by the SHM Engineer Assistant based on S-N curve accumulators and Miner's linear damage rule proxies to assist inspection engineers.*
"""
    return explanation.strip()
